"""Robot Framework locator and code generator.
Supports both Browser Library (Playwright-based) and SeleniumLibrary formats.
"""

from __future__ import annotations

import re
import unicodedata
from typing import Any, Dict, List, Optional


def sanitize_variable_name(raw_name: str) -> str:
    """Sanitizes text/id/name into a clean Robot Framework variable name in uppercase SNAKE_CASE."""
    if not raw_name:
        return "ELEMENT"

    # Normalize unicode (accents -> ascii)
    normalized = unicodedata.normalize("NFKD", raw_name)
    ascii_str = normalized.encode("ascii", "ignore").decode("ascii")

    # Replace special characters with underscores
    cleaned = re.sub(r"[^\w\s-]", "", ascii_str)
    snake = re.sub(r"[-\s]+", "_", cleaned).strip("_").upper()

    return snake if snake else "ELEMENT"


def is_likely_dynamic_id(element_id: str) -> bool:
    """Detects if an ID is dynamically generated by frameworks (React, ExtJS, GUIDs, etc.)
    and thus fragile for test automation.
    """
    if not element_id:
        return True

    # React 18 useId format: :r0:, :r1:, etc.
    if re.match(r"^:r[0-9a-zA-Z]+:$", element_id):
        return True

    # Pure numbers or ending in long timestamp/random number
    if element_id.isdigit():
        return True
    if re.search(r"[-_]\d{5,}$", element_id):
        return True

    # Hex / UUID / GUID patterns
    if re.search(r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}", element_id):
        return True
    if re.search(r"[0-9a-fA-F]{12,}", element_id):
        return True

    # Known framework dynamic patterns
    if re.match(r"^(ext-gen|ember|ui-id|gwt-uid|rc-tabs|_ngcontent)[-_]?\d+", element_id, re.IGNORECASE):
        return True

    return False


class RobotLocatorGenerator:
    """Generates and prioritizes Robot Framework locators and snippets for DOM elements."""

    @staticmethod
    def generate_variable_name(metadata: Dict[str, Any]) -> str:
        """Generates a standardized Robot Framework variable name like ${BTN_SUBMIT_LOGIN}."""
        tag = metadata.get("tag", "").lower()
        input_type = metadata.get("type", "").lower()
        text = metadata.get("text", "").strip()
        elem_id = metadata.get("id", "").strip()
        name = metadata.get("name", "").strip()
        test_id = metadata.get("testId", "").strip()
        aria_label = metadata.get("ariaLabel", "").strip()
        placeholder = metadata.get("placeholder", "").strip()

        prefix = "ELEM"
        if tag == "button" or (tag == "input" and input_type in ("submit", "button", "reset")):
            prefix = "BTN"
        elif tag == "input":
            if input_type in ("checkbox",):
                prefix = "CHK"
            elif input_type in ("radio",):
                prefix = "RDO"
            elif input_type in ("file",):
                prefix = "UPLOAD"
            else:
                prefix = "INPUT"
        elif tag == "select":
            prefix = "SELECT"
        elif tag == "textarea":
            prefix = "TEXTAREA"
        elif tag == "a":
            prefix = "LINK"
        elif tag in ("table", "tbody", "tr", "td"):
            prefix = "TABLE"
        elif tag in ("h1", "h2", "h3", "h4", "h5", "h6"):
            prefix = "TITLE"
        elif tag in ("dialog", "modal"):
            prefix = "MODAL"

        # Determine descriptive base name
        base = ""
        # Prefer human-readable text for buttons/links/titles
        if tag in ("button", "a", "h1", "h2", "h3") and text and len(text) <= 35:
            base = text
        elif test_id:
            base = test_id
        elif elem_id and not is_likely_dynamic_id(elem_id):
            base = elem_id
        elif name:
            base = name
        elif aria_label:
            base = aria_label
        elif placeholder:
            base = placeholder
        elif text and len(text) <= 30:
            base = text
        else:
            base = f"{tag}_{input_type}" if input_type else tag

        clean_base = sanitize_variable_name(base)
        return f"${{{prefix}_{clean_base}}}"

    @classmethod
    def generate_locators(cls, metadata: Dict[str, Any]) -> Dict[str, Any]:
        """Calculates prioritized locators for both Browser Library and SeleniumLibrary."""
        tag = metadata.get("tag", "").lower()
        elem_id = metadata.get("id", "").strip()
        name = metadata.get("name", "").strip()
        test_id = metadata.get("testId", "").strip()
        text = metadata.get("text", "").strip()
        role = metadata.get("role", "").strip()
        aria_label = metadata.get("ariaLabel", "").strip()
        placeholder = metadata.get("placeholder", "").strip()
        css_selector = metadata.get("cssSelector", "").strip()
        xpath = metadata.get("xpath", "").strip()

        # -------------------------------------------------------------
        # 1. Robot Framework - Browser Library (Playwright under the hood)
        # -------------------------------------------------------------
        browser_locators: Dict[str, str] = {}

        if test_id:
            browser_locators["by_test_id"] = f'[data-testid="{test_id}"]'
        
        if elem_id and not is_likely_dynamic_id(elem_id):
            browser_locators["by_id"] = f"id={elem_id}"

        role_name = aria_label or (text if len(text) <= 30 else "")
        if role and role_name:
            browser_locators["by_role"] = f'role={role}[name="{role_name}"]'
        elif tag == "button" and text and len(text) <= 30:
            browser_locators["by_role"] = f'role=button[name="{text}"]'

        if text and len(text) <= 40 and tag in ("button", "a", "span", "p", "h1", "h2", "h3", "label"):
            clean_text = text.replace('"', '\\"')
            browser_locators["by_text"] = f'text="{clean_text}"'

        if placeholder:
            browser_locators["by_placeholder"] = f'[placeholder="{placeholder}"]'

        if name:
            browser_locators["by_name"] = f'[name="{name}"]'

        if css_selector:
            browser_locators["css"] = f"css={css_selector}" if not css_selector.startswith("css=") else css_selector

        if xpath:
            browser_locators["xpath"] = f"xpath={xpath}" if not xpath.startswith("xpath=") else xpath

        # Determine best Browser Library locator based on QA best practices
        best_browser = (
            browser_locators.get("by_test_id")
            or browser_locators.get("by_id")
            or browser_locators.get("by_role")
            or browser_locators.get("by_placeholder")
            or browser_locators.get("by_name")
            or browser_locators.get("by_text")
            or browser_locators.get("css")
            or browser_locators.get("xpath")
            or tag
        )

        # -------------------------------------------------------------
        # 2. Robot Framework - SeleniumLibrary
        # -------------------------------------------------------------
        selenium_locators: Dict[str, str] = {}

        if elem_id and not is_likely_dynamic_id(elem_id):
            selenium_locators["by_id"] = f"id:{elem_id}"

        if name:
            selenium_locators["by_name"] = f"name:{name}"

        if test_id:
            selenium_locators["by_test_id"] = f'css:[data-testid="{test_id}"]'

        if tag == "a" and text and len(text) <= 40:
            selenium_locators["by_link"] = f"link:{text}"

        if css_selector:
            clean_css = css_selector.removeprefix("css=")
            selenium_locators["css"] = f"css:{clean_css}"

        if xpath:
            clean_xpath = xpath.removeprefix("xpath=")
            selenium_locators["xpath"] = f"xpath:{clean_xpath}"

        # Determine best Selenium locator
        best_selenium = (
            selenium_locators.get("by_id")
            or selenium_locators.get("by_test_id")
            or selenium_locators.get("by_name")
            or selenium_locators.get("by_link")
            or selenium_locators.get("css")
            or selenium_locators.get("xpath")
            or tag
        )

        variable_name = cls.generate_variable_name(metadata)

        return {
            "variable_name": variable_name,
            "browser_library": {
                "best": best_browser,
                "options": browser_locators,
            },
            "selenium_library": {
                "best": best_selenium,
                "options": selenium_locators,
            },
        }

    @classmethod
    def generate_keywords(cls, metadata: Dict[str, Any], variable_name: str, library: str = "Browser") -> str:
        """Generates ready-to-use Robot Framework keywords for the element."""
        tag = metadata.get("tag", "").lower()
        input_type = metadata.get("type", "").lower()
        text = metadata.get("text", "").strip()
        elem_name = variable_name.replace("${", "").replace("}", "").replace("_", " ").title()

        lines: List[str] = []

        if library.lower() == "browser":
            if tag == "button" or (tag == "input" and input_type in ("submit", "button")):
                lines.append(f"Click {elem_name}")
                lines.append(f"    [Documentation]    Clica no botão {elem_name}")
                lines.append(f"    Click    {variable_name}")
            elif tag == "input" and input_type == "checkbox":
                lines.append(f"Check {elem_name}")
                lines.append(f"    [Documentation]    Marca a caixa de seleção {elem_name}")
                lines.append(f"    Check Checkbox    {variable_name}")
            elif tag == "input" and input_type == "radio":
                lines.append(f"Select {elem_name}")
                lines.append(f"    [Documentation]    Seleciona a opção {elem_name}")
                lines.append(f"    Check Checkbox    {variable_name}")
            elif tag in ("input", "textarea"):
                lines.append(f"Fill {elem_name}")
                lines.append(f"    [Arguments]    ${{value}}")
                lines.append(f"    [Documentation]    Preenche o campo {elem_name} com o valor informado")
                lines.append(f"    Fill Text    {variable_name}    ${{value}}")
            elif tag == "select":
                lines.append(f"Select From {elem_name}")
                lines.append(f"    [Arguments]    ${{option_value}}")
                lines.append(f"    [Documentation]    Seleciona uma opção no dropdown {elem_name}")
                lines.append(f"    Select Options By    {variable_name}    value    ${{option_value}}")
            elif tag == "a":
                lines.append(f"Click {elem_name} Link")
                lines.append(f"    [Documentation]    Clica no link {elem_name}")
                lines.append(f"    Click    {variable_name}")
            else:
                lines.append(f"Validate {elem_name} Is Visible")
                lines.append(f"    [Documentation]    Verifica se {elem_name} está visível na tela")
                lines.append(f"    Wait For Elements State    {variable_name}    visible    timeout=10s")
        else:
            # SeleniumLibrary
            if tag == "button" or (tag == "input" and input_type in ("submit", "button")):
                lines.append(f"Click {elem_name}")
                lines.append(f"    [Documentation]    Clica no botão {elem_name}")
                lines.append(f"    Click Button    {variable_name}")
            elif tag == "input" and input_type == "checkbox":
                lines.append(f"Select {elem_name}")
                lines.append(f"    [Documentation]    Marca a caixa de seleção {elem_name}")
                lines.append(f"    Select Checkbox    {variable_name}")
            elif tag in ("input", "textarea"):
                lines.append(f"Input {elem_name}")
                lines.append(f"    [Arguments]    ${{value}}")
                lines.append(f"    [Documentation]    Digita no campo {elem_name}")
                lines.append(f"    Input Text    {variable_name}    ${{value}}")
            elif tag == "select":
                lines.append(f"Select From {elem_name}")
                lines.append(f"    [Arguments]    ${{option_value}}")
                lines.append(f"    [Documentation]    Seleciona uma opção no dropdown {elem_name}")
                lines.append(f"    Select From List By Value    {variable_name}    ${{option_value}}")
            elif tag == "a":
                lines.append(f"Click {elem_name} Link")
                lines.append(f"    [Documentation]    Clica no link {elem_name}")
                lines.append(f"    Click Link    {variable_name}")
            else:
                lines.append(f"Validate {elem_name} Is Visible")
                lines.append(f"    [Documentation]    Verifica se {elem_name} está visível na tela")
                lines.append(f"    Element Should Be Visible    {variable_name}")

        return "\n".join(lines)
